### ISSUE TITLE
pip install PyTableGen

### ISSUE THREAD

**Issue by kyleomalley** [daeken/WebStation#5]
```
from tblgen import interpret, Dag, TableGenBits
```

ImportError: No module named tblgen
127.0.0.1 - - [14/Feb/2016 12:17:57] "GET /decomp.js HTTP/1.1" 200 -

**Comment by daeken** [comment]
Ah hah, good catch.  Installation also depends on the PyTableGen module.  Adding to the readme now.  Thanks!

**Comment by daeken** [comment]
Fixed in f8df6bbec053f6af59c9d2a48ff10fa252789d27.
